% -------------------------------------------------------------------
%  Generated by MATLAB on 2-Mar-2020 09:13:27
%  MATLAB version: 9.6.0.1150989 (R2019a) Update 4
% -------------------------------------------------------------------
saveVarsMat = load('A2_q6.mat');

CSTest = saveVarsMat.CSTest; % <1x32619 double> too many elements

CSTrain = saveVarsMat.CSTrain; % <1x60128 double> too many elements

CVTest = saveVarsMat.CVTest; % <1x32619 double> too many elements

CVTrain = saveVarsMat.CVTrain; % <1x60128 double> too many elements

DeltaTest = saveVarsMat.DeltaTest; % <32619x1 double> too many elements

DeltaTrain = saveVarsMat.DeltaTrain; % <60128x1 double> too many elements

STest = saveVarsMat.STest; % <32619x1 double> too many elements

STrain = saveVarsMat.STrain; % <60128x1 double> too many elements

T = ...
  [0 0 0;
   1 0 0;
   2 0 0;
   0 1 0;
   0 2 0;
   1 1 0];

TauTest = saveVarsMat.TauTest; % <32619x1 double> too many elements

TauTrain = saveVarsMat.TauTrain; % <60128x1 double> too many elements

VegaTest = saveVarsMat.VegaTest; % <32619x1 double> too many elements

VegaTrain = saveVarsMat.VegaTrain; % <60128x1 double> too many elements

X = saveVarsMat.X; % <60128x2 double> too many elements

delta = saveVarsMat.delta; % <60128x1 double> too many elements

delta_S = saveVarsMat.delta_S; % <1x60128 double> too many elements

delta_V = saveVarsMat.delta_V; % <1x60128 double> too many elements

error = saveVarsMat.error; % <60128x1 double> too many elements

error_1 = saveVarsMat.error_1; % <30064x30064 double> too many elements

error_2 = saveVarsMat.error_2; % <30064x30064 double> too many elements

lm = saveVarsMat.lm; % <1x1 LinearModel> unsupported class

x1 = saveVarsMat.x1; % <60128x1 double> too many elements

x2 = saveVarsMat.x2; % <60128x1 double> too many elements

clear saveVarsMat;
